// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Page documents */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  meta_description: prismic.RichTextField;
  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = HeroSlice | SobreNosSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
export type AllDocumentTypes = PageDocument;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
  /**
   * Titulo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Titulo da tela principal
   * - **API ID Path**: hero.primary.titulo
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  titulo: prismic.RichTextField;
  /**
   * Subtitulo field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Subtítulo da tela principal
   * - **API ID Path**: hero.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  subtitulo: prismic.RichTextField;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;
/**
 * Primary content in SobreNos → Primary
 *
 */
interface SobreNosSliceDefaultPrimary {
  /**
   * Titulo field in *SobreNos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Título da seção "Sobre Nós"
   * - **API ID Path**: sobre_nos.primary.titulo
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  titulo: prismic.RichTextField;
  /**
   * Imagem field in *SobreNos → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.primary.imagem
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  imagem: prismic.ImageField<never>;
  /**
   * Texto field in *SobreNos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrição da empresa
   * - **API ID Path**: sobre_nos.primary.texto
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  texto: prismic.RichTextField;
}
/**
 * Default variation for SobreNos Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SobreNosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SobreNosSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *SobreNos*
 *
 */
type SobreNosSliceVariation = SobreNosSliceDefault;
/**
 * SobreNos Shared Slice
 *
 * - **API ID**: `sobre_nos`
 * - **Description**: `SobreNos`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SobreNosSlice = prismic.SharedSlice<
  "sobre_nos",
  SobreNosSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocument,
      AllDocumentTypes,
      HeroSliceDefaultPrimary,
      HeroSliceDefault,
      HeroSliceVariation,
      HeroSlice,
      SobreNosSliceDefaultPrimary,
      SobreNosSliceDefault,
      SobreNosSliceVariation,
      SobreNosSlice,
    };
  }
}
